name: Video Process

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependent
        run: |
          aria2c https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64
          chmod +x linux-x64
          sudo mv linux-x64  /usr/local/bin/ffmpeg
      
      - name: Setup task
        run: |
            python3 setup.py

      - name: Download video
        run: |
            aria2c --conf-path=./aria2.conf $(cat url.txt)
      
      - name: Process video
        run: |
          du -h $(cat video.txt)
          ffmpeg -hide_banner -loglevel error -i $(cat video.txt) -c:v libx264 -vf scale=-2:720 -c:a copy output.mp4
          du -h output.mp4